package Noah.InfinityBound.itemdata;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.item.Item;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.ItemLilyPad;
import net.minecraft.block.Block;
import net.minecraft.client.renderer.texture.IconRegister;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.ItemTool;
import net.minecraftforge.common.EnumHelper;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.ItemArmor;
import net.minecraft.src.ModLoader;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.*;
import Noah.InfinityBound.InfinityBound;
import Noah.InfinityBound.blockdata.BlockFlowerRainbow;
import Noah.InfinityBound.blockdata.Blocks;
import Noah.InfinityBound.itemdata.*;

public class Items extends Item
{
    public Items(int id)
    {
        super(id);
    }
    public static EnumToolMaterial toolBEDROCK = EnumHelper.addToolMaterial("BEDROCK", 4, 2001, 12.0F, 12, 10);
    public static EnumToolMaterial toolBEDROCKSTONE = EnumHelper.addToolMaterial("BEDROCKSTONE", 4, 2401, 12.0F, 12, 10);
    public static EnumToolMaterial toolBEDROCKIRON = EnumHelper.addToolMaterial("BEDROCKIRON", 4, 3001, 12.0F, 12, 10);
    public static EnumToolMaterial toolBEDROCKGOLD = EnumHelper.addToolMaterial("BEDROCKGOLD", 4, 1801, 13.5F, 13, 10);
    public static EnumToolMaterial toolBEDROCKDIAMOND = EnumHelper.addToolMaterial("BEDROCKDIAMOND", 4, 4002, 12.0F, 12, 10);
    public static EnumToolMaterial toolBEDROCKBEDROCK = EnumHelper.addToolMaterial("BEDROCKBEDROCK", 4, 5002, 12.5F, 13, 10);
    public static EnumToolMaterial toolDIAMONDSTONE = EnumHelper.addToolMaterial("DIAMONDSTONE", 3, 1873, 8.0F, 3, 10);
    public static EnumToolMaterial toolDIAMONDIRON = EnumHelper.addToolMaterial("DIAMONDIRON", 3, 2341, 8.0F, 3, 10);
    public static EnumToolMaterial toolDIAMONDGOLD = EnumHelper.addToolMaterial("DIAMONDGOLD", 3, 1873, 9.5F, 3, 10);
    public static EnumToolMaterial toolDIAMONDDIAMOND = EnumHelper.addToolMaterial("DIAMONDDIAMOND", 3, 3122, 8.0F, 3, 10);
    public static EnumToolMaterial toolDIAMONDBEDROCK = EnumHelper.addToolMaterial("DIAMONDBEDROCK", 3, 3902, 8.5F, 4, 10);
    public static EnumToolMaterial toolGOLDSTONE = EnumHelper.addToolMaterial("GOLDSTONE", 0, 38, 12.0F, 0, 22);
    public static EnumToolMaterial toolGOLDIRON = EnumHelper.addToolMaterial("GOLDIRON", 0, 48, 12.0F, 0, 22);
    public static EnumToolMaterial toolGOLDGOLD = EnumHelper.addToolMaterial("GOLDGOLD", 0, 29, 13.5F, 1, 22);
    public static EnumToolMaterial toolGOLDDIAMOND = EnumHelper.addToolMaterial("GOLDDIAMOND", 0, 64, 12.0F, 0, 22);
    public static EnumToolMaterial toolGOLDBEDROCK = EnumHelper.addToolMaterial("GOLDBEDROCK", 0, 80, 12.5F, 1, 22);
    public static EnumToolMaterial toolIRONSTONE = EnumHelper.addToolMaterial("IRONSTONE", 2, 300, 6.0F, 2, 14);
    public static EnumToolMaterial toolIRONIRON = EnumHelper.addToolMaterial("IRONIRON", 2, 375, 6.0F, 2, 14);
    public static EnumToolMaterial toolIRONGOLD = EnumHelper.addToolMaterial("IRONGOLD", 2, 225, 7.5F, 3, 14);
    public static EnumToolMaterial toolIRONDIAMOND = EnumHelper.addToolMaterial("IRONDIAMOND", 2, 500, 6.0F, 2, 14);
    public static EnumToolMaterial toolIRONBEDROCK = EnumHelper.addToolMaterial("IRONBEDROCK", 2, 625, 6.5F, 3, 14);
    public static EnumToolMaterial toolSTONESTONE = EnumHelper.addToolMaterial("STONESTONE", 1, 157, 4.0F, 1, 5);
    public static EnumToolMaterial toolSTONEIRON = EnumHelper.addToolMaterial("STONEIRON", 1, 196, 4.0F, 1, 5);
    public static EnumToolMaterial toolSTONEGOLD = EnumHelper.addToolMaterial("STONEGOLD", 1, 118, 5.5F, 2, 5);
    public static EnumToolMaterial toolSTONEDIAMOND = EnumHelper.addToolMaterial("STONEDIAMOND", 1, 262, 4.0F, 1, 5);
    public static EnumToolMaterial toolSTONEBEDROCK = EnumHelper.addToolMaterial("STONEBEDROCK", 1, 327, 4.5F, 2, 5);
    public static EnumToolMaterial toolWOODSTONE = EnumHelper.addToolMaterial("WOODSTONE", 0, 71, 2.0F, 0, 15);
    public static EnumToolMaterial toolWOODIRON = EnumHelper.addToolMaterial("WOODIRON", 0, 89, 2.0F, 0, 15);
    public static EnumToolMaterial toolWOODGOLD = EnumHelper.addToolMaterial("WOODGOLD", 0, 53, 3.5F, 1, 15);
    public static EnumToolMaterial toolWOODDIAMOND = EnumHelper.addToolMaterial("WOODDIAMOND", 0, 118, 2.0F, 0, 15);
    public static EnumToolMaterial toolWOODBEDROCK = EnumHelper.addToolMaterial("WOODBEDROCK", 0, 148, 2.5F, 1, 15);
    public static EnumToolMaterial toolINSTAKILL = EnumHelper.addToolMaterial("INSTAKILL", 0, 5, 1.0F, 37, 0);
    public static EnumToolMaterial toolINFINITY = EnumHelper.addToolMaterial("INFINITY", 4, 0, 18.0F, 22, 10);
    public static EnumToolMaterial toolTFARCENIM = EnumHelper.addToolMaterial("TFARCENIM", 2, 400, 7.0F, 2, 14);
    public static EnumArmorMaterial armorBEDROCK = EnumHelper.addArmorMaterial("BEDROCK", 75, new int[] {5, 12, 9, 4}, 10);
    public static final Item piecesBedrock = (new ItemBasic(800).setUnlocalizedName("piecesBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item stickStone = (new ItemStick(801, 2).setUnlocalizedName("stickStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeBedrock = (new ItemPickaxe(802, toolBEDROCK, 1, 6).setUnlocalizedName("pickaxeBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeStoneBedrock = (new ItemPickaxe(803, toolBEDROCKSTONE, 2, 6).setUnlocalizedName("pickaxeStoneBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordBedrock = (new ItemSword(804, toolBEDROCK, 1, 6).setUnlocalizedName("swordBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordStoneBedrock = (new ItemSword(805, toolBEDROCKSTONE, 2, 6).setUnlocalizedName("swordStoneBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item ingotTfarcenim = (new ItemBasic(806).setUnlocalizedName("ingotTfarcenim").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeIronBedrock = (new ItemPickaxe(807, toolBEDROCKIRON, 3, 6).setUnlocalizedName("pickaxeIronBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeGoldBedrock = (new ItemPickaxe(808, toolBEDROCKGOLD, 4, 6).setUnlocalizedName("pickaxeGoldBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeDiamondBedrock = (new ItemPickaxe(809, toolBEDROCKDIAMOND, 5, 6).setUnlocalizedName("pickaxeDiamondBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeBedrockBedrock = (new ItemPickaxe(810, toolBEDROCKBEDROCK, 6, 6).setUnlocalizedName("pickaxeBedrockBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item stickIron = (new ItemStick(811, 3).setUnlocalizedName("stickIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item stickGold = (new ItemStick(812, 4).setUnlocalizedName("stickGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item stickDiamond = (new ItemStick(813, 5).setUnlocalizedName("stickDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item stickBedrock = (new ItemStick(814, 6).setUnlocalizedName("stickBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final BedrockArmor helmetBedrock = (BedrockArmor)(new BedrockArmor(850, armorBEDROCK, 0, 0).setUnlocalizedName("helmetBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final BedrockArmor plateBedrock = (BedrockArmor)(new BedrockArmor(851, armorBEDROCK, 0, 1).setUnlocalizedName("plateBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final BedrockArmor legsBedrock = (BedrockArmor)(new BedrockArmor(852, armorBEDROCK, 0, 2).setUnlocalizedName("legsBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final BedrockArmor bootsBedrock = (BedrockArmor)(new BedrockArmor(853, armorBEDROCK, 0, 3).setUnlocalizedName("bootsBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordIronBedrock = (new ItemSword(855, toolBEDROCKIRON, 0, 4).setUnlocalizedName("swordIronBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordGoldBedrock = (new ItemSword(856, toolBEDROCKGOLD, 4, 6).setUnlocalizedName("swordGoldBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordDiamondBedrock = (new ItemSword(857, toolBEDROCKDIAMOND, 5, 6).setUnlocalizedName("swordDiamondBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordBedrockBedrock = (new ItemSword(858, toolBEDROCKBEDROCK, 6, 6).setUnlocalizedName("swordBedrockBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeBedrock = (new ItemAxe(859, toolBEDROCK, 1, 6).setUnlocalizedName("axeBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeStoneBedrock = (new ItemAxe(860, toolBEDROCKSTONE, 2, 6).setUnlocalizedName("axeStoneBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeIronBedrock = (new ItemAxe(861, toolBEDROCKIRON, 3, 6).setUnlocalizedName("axeIronBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeGoldBedrock = (new ItemAxe(862, toolBEDROCKGOLD, 4, 6).setUnlocalizedName("axeGoldBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeDiamondBedrock = (new ItemAxe(863, toolBEDROCKDIAMOND, 5, 6).setUnlocalizedName("axeDiamondBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeBedrockBedrock = (new ItemAxe(864, toolBEDROCKBEDROCK, 6, 6).setUnlocalizedName("axeBedrockBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeBedrock = (new ItemSpade(865, toolBEDROCK, 1, 6).setUnlocalizedName("spadeBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeStoneBedrock = (new ItemSpade(866, toolBEDROCKSTONE, 2, 6).setUnlocalizedName("spadeStoneBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeIronBedrock = (new ItemSpade(867, toolBEDROCKIRON, 3, 6).setUnlocalizedName("spadeIronBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeGoldBedrock = (new ItemSpade(868, toolBEDROCK, 4, 6).setUnlocalizedName("spadeGoldBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeDiamondBedrock = (new ItemSpade(869, toolBEDROCKDIAMOND, 5, 6).setUnlocalizedName("spadeDiamondBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeBedrockBedrock = (new ItemSpade(870, toolBEDROCKBEDROCK, 6, 6).setUnlocalizedName("spadeBedrockBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeBedrock = (new ItemHoe(871, toolBEDROCK, 1, 6).setUnlocalizedName("hoeBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeStoneBedrock = (new ItemHoe(872, toolBEDROCKSTONE, 2, 6).setUnlocalizedName("hoeStoneBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeIronBedrock = (new ItemHoe(873, toolBEDROCKIRON, 3, 6).setUnlocalizedName("hoeIronBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeGoldBedrock = (new ItemHoe(874, toolBEDROCKGOLD, 4, 6).setUnlocalizedName("hoeGoldBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeDiamondBedrock = (new ItemHoe(875, toolBEDROCKDIAMOND, 5, 6).setUnlocalizedName("hoeDiamondBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeBedrockBedrock = (new ItemHoe(876, toolBEDROCKBEDROCK, 6, 6).setUnlocalizedName("hoeBedrockBedrock").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeStoneDiamond = (new ItemPickaxe(877, toolDIAMONDSTONE, 2, 5).setUnlocalizedName("pickaxeStoneDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeIronDiamond = (new ItemPickaxe(878, toolDIAMONDIRON, 3, 5).setUnlocalizedName("pickaxeIronDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeGoldDiamond = (new ItemPickaxe(879, toolDIAMONDGOLD, 4, 5).setUnlocalizedName("pickaxeGoldDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeDiamondDiamond = (new ItemPickaxe(880, toolDIAMONDDIAMOND, 5, 5).setUnlocalizedName("pickaxeDiamondDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeBedrockDiamond = (new ItemPickaxe(881, toolDIAMONDBEDROCK, 6, 5).setUnlocalizedName("pickaxeBedrockDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordStoneDiamond = (new ItemSword(882, toolDIAMONDSTONE, 2, 5).setUnlocalizedName("swordStoneDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordIronDiamond = (new ItemSword(883, toolDIAMONDIRON, 3, 5).setUnlocalizedName("swordIronDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordGoldDiamond = (new ItemSword(884, toolDIAMONDGOLD, 4, 5).setUnlocalizedName("swordGoldDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordDiamondDiamond = (new ItemSword(885, toolDIAMONDDIAMOND, 5, 5).setUnlocalizedName("swordDiamondDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordBedrockDiamond = (new ItemSword(886, toolDIAMONDBEDROCK, 6, 5).setUnlocalizedName("swordBedrockDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeStoneDiamond = (new ItemAxe(887, toolDIAMONDSTONE, 2, 5).setUnlocalizedName("axeStoneDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeIronDiamond = (new ItemAxe(888, toolDIAMONDIRON, 3, 5).setUnlocalizedName("axeIronDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeGoldDiamond = (new ItemAxe(889, toolDIAMONDGOLD, 4, 5).setUnlocalizedName("axeGoldDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeDiamondDiamond = (new ItemAxe(890, toolDIAMONDDIAMOND, 5, 5).setUnlocalizedName("axeDiamondDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeBedrockDiamond = (new ItemAxe(891, toolDIAMONDBEDROCK, 6, 5).setUnlocalizedName("axeBedrockDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeStoneDiamond = (new ItemSpade(892, toolDIAMONDSTONE, 2, 5).setUnlocalizedName("spadeStoneDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeIronDiamond = (new ItemSpade(893, toolDIAMONDIRON, 3, 5).setUnlocalizedName("spadeIronDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeGoldDiamond = (new ItemSpade(894, toolDIAMONDGOLD, 4, 5).setUnlocalizedName("spadeGoldDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeDiamondDiamond = (new ItemSpade(895, toolDIAMONDDIAMOND, 5, 5).setUnlocalizedName("spadeDiamondDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeBedrockDiamond = (new ItemSpade(896, toolDIAMONDBEDROCK, 6, 5).setUnlocalizedName("spadeBedrockDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeStoneDiamond = (new ItemHoe(897, toolDIAMONDSTONE, 2, 5).setUnlocalizedName("hoeStoneDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeIronDiamond = (new ItemHoe(898, toolDIAMONDIRON, 3, 5).setUnlocalizedName("hoeIronDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeGoldDiamond = (new ItemHoe(899, toolDIAMONDGOLD, 4, 5).setUnlocalizedName("hoeGoldDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeDiamondDiamond = (new ItemHoe(900, toolDIAMONDDIAMOND, 5, 5).setUnlocalizedName("hoeDiamondDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeBedrockDiamond = (new ItemHoe(901, toolDIAMONDBEDROCK, 6, 5).setUnlocalizedName("hoeBedrockDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeStoneGold = (new ItemPickaxe(902, toolGOLDSTONE, 2, 4).setUnlocalizedName("pickaxeStoneGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeIronGold = (new ItemPickaxe(903, toolGOLDIRON, 3, 4).setUnlocalizedName("pickaxeIronGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeGoldGold = (new ItemPickaxe(904, toolGOLDGOLD, 4, 4).setUnlocalizedName("pickaxeGoldGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeDiamondGold = (new ItemPickaxe(905, toolDIAMONDGOLD, 5, 4).setUnlocalizedName("pickaxeDiamondGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeBedrockGold = (new ItemPickaxe(906, toolGOLDBEDROCK, 6, 4).setUnlocalizedName("pickaxeBedrockGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordStoneGold = (new ItemSword(907, toolGOLDSTONE, 2, 4).setUnlocalizedName("swordStoneGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordIronGold = (new ItemSword(908, toolGOLDIRON, 3, 4).setUnlocalizedName("swordIronGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordGoldGold = (new ItemSword(909, toolGOLDGOLD, 4, 4).setUnlocalizedName("swordGoldGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordDiamondGold = (new ItemSword(910, toolGOLDDIAMOND, 5, 4).setUnlocalizedName("swordDiamondGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordBedrockGold = (new ItemSword(911, toolGOLDBEDROCK, 6, 4).setUnlocalizedName("swordBedrockGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeStoneGold = (new ItemAxe(912, toolGOLDSTONE, 2, 4).setUnlocalizedName("axeStoneGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeIronGold = (new ItemAxe(913, toolGOLDIRON, 3, 4).setUnlocalizedName("axeIronGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeGoldGold = (new ItemAxe(914, toolGOLDGOLD, 4, 4).setUnlocalizedName("axeGoldGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeDiamondGold = (new ItemAxe(915, toolGOLDDIAMOND, 5, 4).setUnlocalizedName("axeDiamondGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeBedrockGold = (new ItemAxe(916, toolGOLDBEDROCK, 6, 4).setUnlocalizedName("axeBedrockGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeStoneGold = (new ItemSpade(917, toolGOLDSTONE, 2, 4).setUnlocalizedName("spadeStoneGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeIronGold = (new ItemSpade(918, toolGOLDIRON, 3, 4).setUnlocalizedName("spadeIronGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeGoldGold = (new ItemSpade(919, toolGOLDGOLD, 4, 4).setUnlocalizedName("spadeGoldGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeDiamondGold = (new ItemSpade(920, toolGOLDDIAMOND, 5, 4).setUnlocalizedName("spadeDiamondGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeBedrockGold = (new ItemSpade(921, toolGOLDBEDROCK, 6, 4).setUnlocalizedName("spadeBedrockGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeStoneGold = (new ItemHoe(922, toolGOLDSTONE, 2, 4).setUnlocalizedName("hoeStoneGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeIronGold = (new ItemHoe(923, toolGOLDIRON, 3, 4).setUnlocalizedName("hoeIronGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeGoldGold = (new ItemHoe(924, toolGOLDGOLD, 4, 4).setUnlocalizedName("hoeGoldGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeDiamondGold = (new ItemHoe(925, toolGOLDDIAMOND, 5, 4).setUnlocalizedName("hoeDiamondGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeBedrockGold = (new ItemHoe(926, toolGOLDBEDROCK, 6, 4).setUnlocalizedName("hoeBedrockGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeStoneIron = (new ItemPickaxe(927, toolIRONSTONE, 2, 3).setUnlocalizedName("pickaxeStoneIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeIronIron = (new ItemPickaxe(928, toolIRONIRON, 3, 3).setUnlocalizedName("pickaxeIronIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeGoldIron = (new ItemPickaxe(929, toolIRONGOLD, 4, 3).setUnlocalizedName("pickaxeGoldIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeDiamondIron = (new ItemPickaxe(930, toolIRONDIAMOND, 5, 3).setUnlocalizedName("pickaxeDiamondIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeBedrockIron = (new ItemPickaxe(931, toolIRONBEDROCK, 6, 3).setUnlocalizedName("pickaxeBedrockIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordStoneIron = (new ItemSword(932, toolIRONSTONE, 2, 3).setUnlocalizedName("swordStoneIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordIronIron = (new ItemSword(933, toolIRONIRON, 3, 3).setUnlocalizedName("swordIronIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordGoldIron = (new ItemSword(934, toolIRONGOLD, 4, 3).setUnlocalizedName("swordGoldIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordDiamondIron = (new ItemSword(935, toolIRONDIAMOND, 5, 3).setUnlocalizedName("swordDiamondIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordBedrockIron = (new ItemSword(936, toolIRONBEDROCK, 6, 3).setUnlocalizedName("swordBedrockIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeStoneIron = (new ItemAxe(937, toolIRONSTONE, 2, 3).setUnlocalizedName("axeStoneIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeIronIron = (new ItemAxe(938, toolIRONIRON, 3, 3).setUnlocalizedName("axeIronIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeGoldIron = (new ItemAxe(939, toolIRONGOLD, 4, 3).setUnlocalizedName("axeGoldIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeDiamondIron = (new ItemAxe(940, toolIRONDIAMOND, 5, 3).setUnlocalizedName("axeDiamondIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeBedrockIron = (new ItemAxe(941, toolIRONBEDROCK, 6, 3).setUnlocalizedName("axeBedrockIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeStoneIron = (new ItemSpade(942, toolIRONSTONE, 2, 3).setUnlocalizedName("spadeStoneIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeIronIron = (new ItemSpade(943, toolIRONIRON, 3, 3).setUnlocalizedName("spadeIronIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeGoldIron = (new ItemSpade(944, toolIRONGOLD, 4, 3).setUnlocalizedName("spadeGoldIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeDiamondIron = (new ItemSpade(945, toolIRONDIAMOND, 5, 3).setUnlocalizedName("spadeDiamondIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeBedrockIron = (new ItemSpade(946, toolIRONBEDROCK, 6, 3).setUnlocalizedName("spadeBedrockIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeStoneIron = (new ItemHoe(947, toolIRONSTONE, 2, 3).setUnlocalizedName("hoeStoneIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeIronIron = (new ItemHoe(948, toolIRONIRON, 3, 3).setUnlocalizedName("hoeIronIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeGoldIron = (new ItemHoe(949, toolIRONGOLD, 4, 3).setUnlocalizedName("hoeGoldIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeDiamondIron = (new ItemHoe(950, toolIRONDIAMOND, 5, 3).setUnlocalizedName("hoeDiamondIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeBedrockIron = (new ItemHoe(951, toolIRONBEDROCK, 6, 3).setUnlocalizedName("hoeBedrockIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeStoneStone = (new ItemPickaxe(952, toolSTONESTONE, 2, 2).setUnlocalizedName("pickaxeStoneStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeIronStone = (new ItemPickaxe(953, toolSTONEIRON, 3, 2).setUnlocalizedName("pickaxeIronStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeGoldStone = (new ItemPickaxe(954, toolSTONEGOLD, 4, 2).setUnlocalizedName("pickaxeGoldStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeDiamondStone = (new ItemPickaxe(955, toolSTONEDIAMOND, 5, 2).setUnlocalizedName("pickaxeDiamondStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeBedrockStone = (new ItemPickaxe(956, toolSTONEBEDROCK, 6, 2).setUnlocalizedName("pickaxeBedrockStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordStoneStone = (new ItemSword(957, toolSTONESTONE, 2, 2).setUnlocalizedName("swordStoneStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordIronStone = (new ItemSword(958, toolSTONEIRON, 3, 2).setUnlocalizedName("swordIronStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordGoldStone = (new ItemSword(959, toolSTONEGOLD, 4, 2).setUnlocalizedName("swordGoldStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordDiamondStone = (new ItemSword(960, toolSTONEDIAMOND, 5, 2).setUnlocalizedName("swordDiamondStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordBedrockStone = (new ItemSword(961, toolSTONEBEDROCK, 6, 2).setUnlocalizedName("swordBedrockStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeStoneStone = (new ItemAxe(962, toolSTONESTONE, 2, 2).setUnlocalizedName("axeStoneStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeIronStone = (new ItemAxe(963, toolSTONEIRON, 3, 2).setUnlocalizedName("axeIronStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeGoldStone = (new ItemAxe(964, toolSTONEGOLD, 4, 2).setUnlocalizedName("axeGoldStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeDiamondStone = (new ItemAxe(965, toolSTONEDIAMOND, 5, 2).setUnlocalizedName("axeDiamondStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeBedrockStone = (new ItemAxe(966, toolSTONEBEDROCK, 6, 2).setUnlocalizedName("axeBedrockStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeStoneStone = (new ItemSpade(967, toolSTONESTONE, 2, 2).setUnlocalizedName("spadeStoneStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeIronStone = (new ItemSpade(968, toolSTONEIRON, 3, 2).setUnlocalizedName("spadeIronStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeGoldStone = (new ItemSpade(969, toolSTONEGOLD, 4, 2).setUnlocalizedName("spadeGoldStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeDiamondStone = (new ItemSpade(970, toolSTONEDIAMOND, 5, 2).setUnlocalizedName("spadeDiamondStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeBedrockStone = (new ItemSpade(971, toolSTONEBEDROCK, 6, 2).setUnlocalizedName("spadeBedrockStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeStoneStone = (new ItemHoe(972, toolSTONESTONE, 2, 2).setUnlocalizedName("hoeStoneStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeIronStone = (new ItemHoe(973, toolSTONEIRON, 3, 2).setUnlocalizedName("hoeIronStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeGoldStone = (new ItemHoe(974, toolSTONEGOLD, 4, 2).setUnlocalizedName("hoeGoldStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeDiamondStone = (new ItemHoe(975, toolSTONEDIAMOND, 5, 2).setUnlocalizedName("hoeDiamondStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeBedrockStone = (new ItemHoe(976, toolSTONEBEDROCK, 6, 2).setUnlocalizedName("hoeBedrockStone").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeStoneWood = (new ItemPickaxe(977, toolWOODSTONE, 2, 1).setUnlocalizedName("pickaxeStoneWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeIronWood = (new ItemPickaxe(978, toolWOODIRON, 3, 1).setUnlocalizedName("pickaxeIronWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeGoldWood = (new ItemPickaxe(979, toolWOODGOLD, 4, 1).setUnlocalizedName("pickaxeGoldWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeDiamondWood = (new ItemPickaxe(980, toolWOODDIAMOND, 5, 1).setUnlocalizedName("pickaxeDiamondWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeBedrockWood = (new ItemPickaxe(981, toolWOODBEDROCK, 6, 1).setUnlocalizedName("pickaxeBedrockWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordStoneWood = (new ItemSword(982, toolWOODSTONE, 2, 1).setUnlocalizedName("swordStoneWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordIronWood = (new ItemSword(983, toolWOODIRON, 3, 1).setUnlocalizedName("swordIronWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordGoldWood = (new ItemSword(984, toolWOODGOLD, 4, 1).setUnlocalizedName("swordGoldWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordDiamondWood = (new ItemSword(985, toolWOODDIAMOND, 5, 1).setUnlocalizedName("swordDiamondWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordBedrockWood = (new ItemSword(986, toolWOODBEDROCK, 6, 1).setUnlocalizedName("swordBedrockWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeStoneWood = (new ItemAxe(987, toolWOODSTONE, 2, 1).setUnlocalizedName("axeStoneWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeIronWood = (new ItemAxe(988, toolWOODIRON, 3, 1).setUnlocalizedName("axeIronWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeGoldWood = (new ItemAxe(989, toolWOODGOLD, 4, 1).setUnlocalizedName("axeGoldWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeDiamondWood = (new ItemAxe(990, toolWOODDIAMOND, 5, 1).setUnlocalizedName("axeDiamondWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeBedrockWood = (new ItemAxe(991, toolWOODBEDROCK, 6, 1).setUnlocalizedName("axeBedrockWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeStoneWood = (new ItemSpade(992, toolWOODSTONE, 2, 1).setUnlocalizedName("spadeStoneWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeIronWood = (new ItemSpade(993, toolWOODIRON, 3, 1).setUnlocalizedName("spadeIronWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeGoldWood = (new ItemSpade(994, toolWOODGOLD, 4, 1).setUnlocalizedName("spadeGoldWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeDiamondWood = (new ItemSpade(995, toolWOODDIAMOND, 5, 1).setUnlocalizedName("spadeDiamondWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeBedrockWood = (new ItemSpade(996, toolWOODBEDROCK, 6, 1).setUnlocalizedName("spadeBedrockWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeStoneWood = (new ItemHoe(997, toolWOODSTONE, 2, 1).setUnlocalizedName("hoeStoneWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeIronWood = (new ItemHoe(998, toolWOODIRON, 3, 1).setUnlocalizedName("hoeIronWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeGoldWood = (new ItemHoe(999, toolWOODGOLD, 4, 1).setUnlocalizedName("hoeGoldWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeDiamondWood = (new ItemHoe(1000, toolWOODDIAMOND, 5, 1).setUnlocalizedName("hoeDiamondWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeBedrockWood = (new ItemHoe(1001, toolWOODBEDROCK, 6, 1).setUnlocalizedName("hoeBedrockWood").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordInstaKill = (new ItemSword(609, toolINSTAKILL, 4, 0).setUnlocalizedName("swordInstaKill").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item lambRaw = (new ItemFoodBasic(1002, 2, 0.3F, true).setUnlocalizedName("lambRaw").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item lambCooked = (new ItemFoodBasic(1003, 5, 0.6F, true).setUnlocalizedName("lambCooked").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item crystalNormal = (new ItemBasic(1004).setUnlocalizedName("crystalNormal").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item crystalSuper = (new ItemBasic(1005).setUnlocalizedName("crystalSuper").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item crystalUltra = (new ItemBasic(1006).setUnlocalizedName("crystalUltra").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item crystalInfinity = (new ItemSimpleFoiled(1007).setUnlocalizedName("crystalInfinity").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item swordInfinity = (new ItemInfinitySword(1008, toolINFINITY).setUnlocalizedName("swordInfinity").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item pickaxeInfinity = (new ItemPickaxe(1009, toolINFINITY, 0, 0).setUnlocalizedName("pickaxeInfinity").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item axeInfinity = (new ItemAxe(1010, toolINFINITY, 0, 0).setUnlocalizedName("axeInfinity").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item spadeInfinity = (new ItemSpade(1011, toolINFINITY, 0, 0).setUnlocalizedName("spadeInfinity").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hoeInfinity = (new ItemHoe(1012, toolINFINITY, 0, 0).setUnlocalizedName("hoeInfinity").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item bowInsta = (new InstaBow(1013).setUnlocalizedName("bowInsta").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item stringDiamond = (new ItemBasic(1014).setUnlocalizedName("stringDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item hammer = (new ItemHammer(1015, toolTFARCENIM).setUnlocalizedName("hammer").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item appleSeeds = (new ItemSeeds(1016, Blocks.appleCrop.blockID, Block.tilledField.blockID).setUnlocalizedName("appleSeeds").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item itemFlowerRainbow = (new ItemFlowerRainbow(Blocks.flowerRainbow.blockID - 256));
    public static final Item piecesIron = (new ItemBasic(1017).setUnlocalizedName("piecesIron").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item piecesGold = (new ItemBasic(1018).setUnlocalizedName("piecesGold").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item dyeRainbow = (new ItemBasic(1019).setUnlocalizedName("dyeRainbow").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item piecesTfarcenim = (new ItemBasic(1020).setUnlocalizedName("piecesTfarcenim").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item dustDiamond = (new ItemBasic(1021).setUnlocalizedName("dustDiamond").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item essenceIntangible = (new ItemSimpleFoiled(1022).setUnlocalizedName("essenceIntangible").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item recordSideburns = (new ItemRecord(1023, "Sideburns", "Tobuscus").setUnlocalizedName("recordSideburns").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item crystalNormalFused = (new ItemBasic(1024).setUnlocalizedName("crystalNormalFused").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item crystalSuperFused = (new ItemBasic(1025).setUnlocalizedName("crystalSuperFused").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item crystalUltraFused = (new ItemBasic(1026).setUnlocalizedName("crystalUltraFused").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item crystalInfinityFused = (new ItemSimpleFoiled(1027).setUnlocalizedName("crystalInfinityFused").setCreativeTab(InfinityBound.tabInfinityBound));
    public static final Item recordDramatic = (new ItemRecord(1028, "Dramatic Song", "Tobuscus").setUnlocalizedName("recordDramatic").setCreativeTab(InfinityBound.tabInfinityBound));
}