package Noah.InfinityBound;

import net.minecraft.block.Block;
import net.minecraft.block.BlockFire;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.FurnaceRecipes;
import net.minecraft.src.ModLoader;
import net.minecraft.tileentity.TileEntity;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.client.registry.ISimpleBlockRenderingHandler;
import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import Noah.InfinityBound.blockdata.BlockNetherChest;
import Noah.InfinityBound.blockdata.BlockWoodNoHit;
import Noah.InfinityBound.blockdata.Blocks;
import Noah.InfinityBound.events.BonemealEvent;
import Noah.InfinityBound.events.MobDrops;
import Noah.InfinityBound.events.PlayerEvent;
import Noah.InfinityBound.events.SoundsEvent;
import Noah.InfinityBound.gui.GuiHandler;
import Noah.InfinityBound.itemdata.ItemBlock;
import Noah.InfinityBound.itemdata.ItemHammer;
import Noah.InfinityBound.itemdata.Items;
import Noah.InfinityBound.worldgen.WorldGenHandle;
import Noah.InfinityBound.proxy.CommonProxy;
import Noah.InfinityBound.render.TileEntityNetherChestRenderer;
import Noah.InfinityBound.tileentity.TileEntityCutter;
import Noah.InfinityBound.tileentity.TileEntityFuser;
import Noah.InfinityBound.tileentity.TileEntityNetherChest;

@Mod(modid = "InfinityBound", name = "InfinityBound", version = "1.3.2")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class InfinityBound
{
    @SidedProxy(clientSide = "Noah.InfinityBound.proxy.ClientProxy", serverSide = "Noah.InfinityBound.proxy.CommonProxy")
    public static CommonProxy proxy;

    @Instance("InfinityBound")
    public static InfinityBound instance;

    @EventHandler
    public void load(FMLInitializationEvent event)
    {
        proxy.registerRenderInformation();
        proxy.registerSounds();
        GameRegistry.registerBlock(Blocks.oreBedrock, "oreBedrock");
        GameRegistry.registerBlock(Blocks.oreTfarcenim, "oreTfarcenim");
        GameRegistry.registerBlock(Blocks.blockBedrock, "blockBedrock");
        GameRegistry.registerBlock(Blocks.blockTfarcenim, "blockTfarcenim");
        GameRegistry.registerBlock(Blocks.appleCrop, "appleCrop");
        GameRegistry.registerBlock(Blocks.leaves, "leaves");
        GameRegistry.registerBlock(Blocks.sapling, "sapling");
        GameRegistry.registerBlock(Blocks.flowerRainbow, "blockFlowerRainbow");
        GameRegistry.registerBlock(Blocks.stoneNoHit, "stoneNoHit");
        GameRegistry.registerBlock(Blocks.cobblestoneNoHit, "cobblestoneNoHit");
        GameRegistry.registerBlock(Blocks.cutter, "cutter");
        GameRegistry.registerBlock(Blocks.woolRainbow, "woolRainbow");
        GameRegistry.registerBlock(Blocks.oreIntangible, "oreIntangible");
        GameRegistry.registerBlock(Blocks.woolRainbowNoHit, "woolRainbowNoHit");
        GameRegistry.registerBlock(Blocks.glassNoHit, "glassNoHit");
        GameRegistry.registerBlock(Blocks.planksNoHit, ItemBlock.class, "InfinityBound" + (Blocks.planksNoHit.getUnlocalizedName().substring(5)));
        GameRegistry.registerBlock(Blocks.chestNether, "chestNether");
        GameRegistry.registerBlock(Blocks.fuser, "fuser");
        GameRegistry.registerItem(Items.piecesBedrock, "piecesBedrock");
        GameRegistry.registerItem(Items.stickStone, "stickStone");
        GameRegistry.registerItem(Items.pickaxeBedrock, "pickaxeBedrock");
        GameRegistry.registerItem(Items.pickaxeStoneBedrock, "pickaxeStoneBedrock");
        GameRegistry.registerItem(Items.swordBedrock, "swordBedrock");
        GameRegistry.registerItem(Items.swordStoneBedrock, "swordStoneBedrock");
        GameRegistry.registerItem(Items.stickIron, "stickIron");
        GameRegistry.registerItem(Items.stickGold, "stickGold");
        GameRegistry.registerItem(Items.stickDiamond, "stickDiamond");
        GameRegistry.registerItem(Items.stickBedrock, "stickBedrock");
        GameRegistry.registerItem(Items.pickaxeIronBedrock, "pickaxeIronBedrock");
        GameRegistry.registerItem(Items.pickaxeGoldBedrock, "pickaxeGoldBedrock");
        GameRegistry.registerItem(Items.pickaxeDiamondBedrock, "pickaxeDiamondBedrock");
        GameRegistry.registerItem(Items.pickaxeBedrockBedrock, "pickaxeBedrockBedrock");
        GameRegistry.registerItem(Items.helmetBedrock, "helmetBedrock");
        GameRegistry.registerItem(Items.plateBedrock, "plateBedrock");
        GameRegistry.registerItem(Items.legsBedrock, "legsBedrock");
        GameRegistry.registerItem(Items.bootsBedrock, "bootsBedrock");
        GameRegistry.registerItem(Items.swordIronBedrock, "swordIronBedrock");
        GameRegistry.registerItem(Items.swordGoldBedrock, "swordGoldBedrock");
        GameRegistry.registerItem(Items.swordDiamondBedrock, "swordDiamondBedrock");
        GameRegistry.registerItem(Items.swordBedrockBedrock, "swordBedrockBedrock");
        GameRegistry.registerItem(Items.spadeBedrock, "spadeBedrock");
        GameRegistry.registerItem(Items.spadeStoneBedrock, "spadeStoneBedrock");
        GameRegistry.registerItem(Items.spadeIronBedrock, "spadeIronBedrock");
        GameRegistry.registerItem(Items.spadeDiamondBedrock, "spadeDiamondBedrock");
        GameRegistry.registerItem(Items.spadeBedrockBedrock, "spadeBedrockBedrock");
        GameRegistry.registerItem(Items.hoeBedrock, "hoeBedrock");
        GameRegistry.registerItem(Items.hoeStoneBedrock, "hoeStoneBedrock");
        GameRegistry.registerItem(Items.hoeIronBedrock, "hoeIronBedrock");
        GameRegistry.registerItem(Items.hoeGoldBedrock, "hoeGoldBedrock");
        GameRegistry.registerItem(Items.hoeDiamondBedrock, "hoeDiamondBedrock");
        GameRegistry.registerItem(Items.hoeBedrockBedrock, "hoeBedrockBedrock");
        GameRegistry.registerItem(Items.axeBedrock, "axeBedrock");
        GameRegistry.registerItem(Items.axeStoneBedrock, "axeStoneBedrock");
        GameRegistry.registerItem(Items.axeIronBedrock, "axeIronBedrock");
        GameRegistry.registerItem(Items.axeGoldBedrock, "axeGoldBedrock");
        GameRegistry.registerItem(Items.axeDiamondBedrock, "axeDiamondBedrock");
        GameRegistry.registerItem(Items.axeBedrockBedrock, "axeBedrockBedrock");
        GameRegistry.registerItem(Items.pickaxeStoneDiamond, "pickaxeStoneDiamond");
        GameRegistry.registerItem(Items.pickaxeIronDiamond, "pickaxeIronDiamond");
        GameRegistry.registerItem(Items.pickaxeGoldDiamond, "pickaxeGoldDiamond");
        GameRegistry.registerItem(Items.pickaxeDiamondDiamond, "pickaxeDiamondDiamond");
        GameRegistry.registerItem(Items.pickaxeBedrockDiamond, "pickaxeBedrockDiamond");
        GameRegistry.registerItem(Items.swordStoneDiamond, "swordStoneDiamond");
        GameRegistry.registerItem(Items.swordIronDiamond, "swordIronDiamond");
        GameRegistry.registerItem(Items.swordGoldDiamond, "swordGoldDiamond");
        GameRegistry.registerItem(Items.swordDiamondDiamond, "swordDiamondDiamond");
        GameRegistry.registerItem(Items.swordBedrockDiamond, "swordBedrockDiamond");
        GameRegistry.registerItem(Items.axeStoneDiamond, "axeStoneDiamond");
        GameRegistry.registerItem(Items.axeIronDiamond, "axeIronDiamond");
        GameRegistry.registerItem(Items.axeGoldDiamond, "axeGoldDiamond");
        GameRegistry.registerItem(Items.axeDiamondDiamond, "axeDiamondDiamond");
        GameRegistry.registerItem(Items.axeBedrockDiamond, "axeBedrockDiamond");
        GameRegistry.registerItem(Items.spadeStoneDiamond, "spadeStoneDiamond");
        GameRegistry.registerItem(Items.spadeIronDiamond, "spadeIronDiamond");
        GameRegistry.registerItem(Items.spadeGoldDiamond, "spadeGoldDiamond");
        GameRegistry.registerItem(Items.spadeDiamondDiamond, "spadeDiamondDiamond");
        GameRegistry.registerItem(Items.spadeBedrockDiamond, "spadeBedrockDiamond");
        GameRegistry.registerItem(Items.hoeStoneDiamond, "hoeStoneDiamond");
        GameRegistry.registerItem(Items.hoeIronDiamond, "hoeIronDiamond");
        GameRegistry.registerItem(Items.hoeGoldDiamond, "hoeGoldDiamond");
        GameRegistry.registerItem(Items.hoeDiamondDiamond, "hoeDiamondDiamond");
        GameRegistry.registerItem(Items.hoeBedrockDiamond, "hoeBedrockDiamond");
        GameRegistry.registerItem(Items.pickaxeStoneGold, "pickaxeStoneGold");
        GameRegistry.registerItem(Items.pickaxeIronGold, "pickaxeIronGold");
        GameRegistry.registerItem(Items.pickaxeGoldGold, "pickaxeGoldGold");
        GameRegistry.registerItem(Items.pickaxeDiamondGold, "pickaxeDiamondGold");
        GameRegistry.registerItem(Items.pickaxeBedrockGold, "pickaxeBedrockGold");
        GameRegistry.registerItem(Items.swordStoneGold, "swordStoneGold");
        GameRegistry.registerItem(Items.swordIronGold, "swordIronGold");
        GameRegistry.registerItem(Items.swordGoldGold, "swordGoldGold");
        GameRegistry.registerItem(Items.swordDiamondGold, "swordDiamondGold");
        GameRegistry.registerItem(Items.swordBedrockGold, "swordBedrockGold");
        GameRegistry.registerItem(Items.axeStoneGold, "axeStoneGold");
        GameRegistry.registerItem(Items.axeIronGold, "axeIronGold");
        GameRegistry.registerItem(Items.axeGoldGold, "axeGoldGold");
        GameRegistry.registerItem(Items.axeDiamondGold, "axeDiamondGold");
        GameRegistry.registerItem(Items.axeBedrockGold, "axeBedrockGold");
        GameRegistry.registerItem(Items.spadeStoneGold, "spadeStoneGold");
        GameRegistry.registerItem(Items.spadeIronGold, "spadeIronGold");
        GameRegistry.registerItem(Items.spadeGoldGold, "spadeGoldGold");
        GameRegistry.registerItem(Items.spadeDiamondGold, "spadeDiamondGold");
        GameRegistry.registerItem(Items.spadeBedrockGold, "spadeBedrockGold");
        GameRegistry.registerItem(Items.hoeStoneGold, "hoeStoneGold");
        GameRegistry.registerItem(Items.hoeIronGold, "hoeIronGold");
        GameRegistry.registerItem(Items.hoeGoldGold, "hoeGoldGold");
        GameRegistry.registerItem(Items.hoeDiamondGold, "hoeDiamondGold");
        GameRegistry.registerItem(Items.hoeBedrockGold, "hoeBedrockGold");
        GameRegistry.registerItem(Items.pickaxeStoneIron, "pickaxeStoneIron");
        GameRegistry.registerItem(Items.pickaxeIronIron, "pickaxeIronIron");
        GameRegistry.registerItem(Items.pickaxeGoldIron, "pickaxeGoldIron");
        GameRegistry.registerItem(Items.pickaxeDiamondIron, "pickaxeDiamondIron");
        GameRegistry.registerItem(Items.pickaxeBedrockIron, "pickaxeBedrockIron");
        GameRegistry.registerItem(Items.swordStoneIron, "swordStoneIron");
        GameRegistry.registerItem(Items.swordIronIron, "swordIronIron");
        GameRegistry.registerItem(Items.swordGoldIron, "swordGoldIron");
        GameRegistry.registerItem(Items.swordDiamondIron, "swordDiamondIron");
        GameRegistry.registerItem(Items.swordBedrockIron, "swordBedrockIron");
        GameRegistry.registerItem(Items.axeStoneIron, "axeStoneIron");
        GameRegistry.registerItem(Items.axeIronIron, "axeIronIron");
        GameRegistry.registerItem(Items.axeGoldIron, "axeGoldIron");
        GameRegistry.registerItem(Items.axeDiamondIron, "axeDiamondIron");
        GameRegistry.registerItem(Items.axeBedrockIron, "axeBedrockIron");
        GameRegistry.registerItem(Items.spadeStoneIron, "spadeStoneIron");
        GameRegistry.registerItem(Items.spadeIronIron, "spadeIronIron");
        GameRegistry.registerItem(Items.spadeGoldIron, "spadeGoldIron");
        GameRegistry.registerItem(Items.spadeDiamondIron, "spadeDiamondIron");
        GameRegistry.registerItem(Items.spadeBedrockIron, "spadeBedrockIron");
        GameRegistry.registerItem(Items.hoeStoneIron, "hoeStoneIron");
        GameRegistry.registerItem(Items.hoeIronIron, "hoeIronIron");
        GameRegistry.registerItem(Items.hoeGoldIron, "hoeGoldIron");
        GameRegistry.registerItem(Items.hoeDiamondIron, "hoeDiamondIron");
        GameRegistry.registerItem(Items.hoeBedrockIron, "hoeBedrockIron");
        GameRegistry.registerItem(Items.pickaxeStoneStone, "pickaxeStoneStone");
        GameRegistry.registerItem(Items.pickaxeIronStone, "pickaxeIronStone");
        GameRegistry.registerItem(Items.pickaxeGoldStone, "pickaxeGoldStone");
        GameRegistry.registerItem(Items.pickaxeDiamondStone, "pickaxeDiamondStone");
        GameRegistry.registerItem(Items.pickaxeBedrockStone, "pickaxeBedrockStone");
        GameRegistry.registerItem(Items.swordStoneStone, "swordStoneStone");
        GameRegistry.registerItem(Items.swordIronStone, "swordIronStone");
        GameRegistry.registerItem(Items.swordGoldStone, "swordGoldStone");
        GameRegistry.registerItem(Items.swordDiamondStone, "swordDiamondStone");
        GameRegistry.registerItem(Items.swordBedrockStone, "swordBedrockStone");
        GameRegistry.registerItem(Items.axeStoneStone, "axeStoneStone");
        GameRegistry.registerItem(Items.axeIronStone, "axeIronStone");
        GameRegistry.registerItem(Items.axeGoldStone, "axeGoldStone");
        GameRegistry.registerItem(Items.axeDiamondStone, "axeDiamondStone");
        GameRegistry.registerItem(Items.axeBedrockStone, "axeBedrockStone");
        GameRegistry.registerItem(Items.spadeStoneStone, "spadeStoneStone");
        GameRegistry.registerItem(Items.spadeIronStone, "spadeIronStone");
        GameRegistry.registerItem(Items.spadeGoldStone, "spadeGoldStone");
        GameRegistry.registerItem(Items.spadeDiamondStone, "spadeDiamondStone");
        GameRegistry.registerItem(Items.spadeBedrockStone, "spadeBedrockStone");
        GameRegistry.registerItem(Items.hoeStoneStone, "hoeStoneStone");
        GameRegistry.registerItem(Items.hoeIronStone, "hoeIronStone");
        GameRegistry.registerItem(Items.hoeGoldStone, "hoeGoldStone");
        GameRegistry.registerItem(Items.hoeDiamondStone, "hoeDiamondStone");
        GameRegistry.registerItem(Items.hoeBedrockStone, "hoeBedrockStone");
        GameRegistry.registerItem(Items.pickaxeStoneWood, "pickaxeStoneWood");
        GameRegistry.registerItem(Items.pickaxeIronWood, "pickaxeIronWood");
        GameRegistry.registerItem(Items.pickaxeGoldWood, "pickaxeGoldWood");
        GameRegistry.registerItem(Items.pickaxeDiamondWood, "pickaxeDiamondWood");
        GameRegistry.registerItem(Items.pickaxeBedrockWood, "pickaxeBedrockWood");
        GameRegistry.registerItem(Items.swordStoneWood, "swordStoneWood");
        GameRegistry.registerItem(Items.swordIronWood, "swordIronWood");
        GameRegistry.registerItem(Items.swordGoldWood, "swordGoldWood");
        GameRegistry.registerItem(Items.swordDiamondWood, "swordDiamondWood");
        GameRegistry.registerItem(Items.swordBedrockWood, "swordBedrockWood");
        GameRegistry.registerItem(Items.axeStoneWood, "axeStoneWood");
        GameRegistry.registerItem(Items.axeIronWood, "axeIronWood");
        GameRegistry.registerItem(Items.axeGoldWood, "axeGoldWood");
        GameRegistry.registerItem(Items.axeDiamondWood, "axeDiamondWood");
        GameRegistry.registerItem(Items.axeBedrockWood, "axeBedrockWood");
        GameRegistry.registerItem(Items.spadeStoneWood, "spadeStoneWood");
        GameRegistry.registerItem(Items.spadeIronWood, "spadeIronWood");
        GameRegistry.registerItem(Items.spadeGoldWood, "spadeGoldWood");
        GameRegistry.registerItem(Items.spadeDiamondWood, "spadeDiamondWood");
        GameRegistry.registerItem(Items.spadeBedrockWood, "spadeBedrockWood");
        GameRegistry.registerItem(Items.hoeStoneWood, "hoeStoneWood");
        GameRegistry.registerItem(Items.hoeIronWood, "hoeIronWood");
        GameRegistry.registerItem(Items.hoeGoldWood, "hoeGoldWood");
        GameRegistry.registerItem(Items.hoeDiamondWood, "hoeDiamondWood");
        GameRegistry.registerItem(Items.hoeBedrockWood, "hoeBedrockWood");
        GameRegistry.registerItem(Items.swordInstaKill, "swordInstaKill");
        GameRegistry.registerItem(Items.lambRaw, "lambRaw");
        GameRegistry.registerItem(Items.lambCooked, "lambCooked");
        GameRegistry.registerItem(Items.swordInfinity, "swordInfinity");
        GameRegistry.registerItem(Items.pickaxeInfinity, "pickaxeInfinity");
        GameRegistry.registerItem(Items.axeInfinity, "axeInfinity");
        GameRegistry.registerItem(Items.spadeInfinity, "spadeInfinity");
        GameRegistry.registerItem(Items.hoeInfinity, "hoeInfinity");
        GameRegistry.registerItem(Items.crystalNormal, "crystalNormal");
        GameRegistry.registerItem(Items.crystalSuper, "crystalSuper");
        GameRegistry.registerItem(Items.crystalUltra, "crystalUltra");
        GameRegistry.registerItem(Items.crystalInfinity, "crystalInfinity");
        GameRegistry.registerItem(Items.bowInsta, "bowInsta");
        GameRegistry.registerItem(Items.appleSeeds, "appleSeeds");
        GameRegistry.registerItem(Items.itemFlowerRainbow, "itemFlowerRainbow");
        GameRegistry.registerItem(Items.piecesGold, "piecesGold");
        GameRegistry.registerItem(Items.piecesIron, "piecesIron");
        GameRegistry.registerItem(Items.dyeRainbow, "dyeRainbow");
        GameRegistry.registerItem(Items.piecesTfarcenim, "piecesTfarcenim");
        GameRegistry.registerItem(Items.dustDiamond, "dustDiamond");
        GameRegistry.registerItem(Items.essenceIntangible, "essenceIntangible");
        GameRegistry.registerItem(Items.recordSideburns, "sideburns");
        GameRegistry.registerItem(Items.crystalNormalFused, "crystalNormalFused");
        GameRegistry.registerItem(Items.hammer, "hammer");
        GameRegistry.registerItem(Items.crystalSuperFused, "crystalSuperFused");
        GameRegistry.registerItem(Items.crystalUltraFused, "crystalUltraFused");
        GameRegistry.registerItem(Items.crystalInfinityFused, "crystaInfinityFused");
        GameRegistry.registerItem(Items.recordDramatic, "recordDramatic");
        LanguageRegistry.instance().addStringLocalization("itemGroup.tabInfinityBound", "en_US", "InfinityBound");
        LanguageRegistry.instance().addStringLocalization("container.chestNether", "en_US", "Nether Chest");
        LanguageRegistry.instance().addStringLocalization("container.cutter", "en_US", "Cutter");
        LanguageRegistry.instance().addStringLocalization("container.fuser", "en_US", "Fuser");
        LanguageRegistry.addName(Blocks.oreBedrock, "Bedrock Ore");
        LanguageRegistry.addName(Blocks.blockBedrock, "Block of Bedrock");
        LanguageRegistry.addName(Blocks.blockTfarcenim, "Block of Tfarcenim");
        LanguageRegistry.addName(Items.piecesBedrock, "Bedrock Pieces");
        LanguageRegistry.addName(Blocks.oreTfarcenim, "Tfarcenim Ore");
        LanguageRegistry.addName(Items.stickStone, "Stone Stick");
        LanguageRegistry.addName(Items.pickaxeBedrock, "Bedrock Pickaxe");
        LanguageRegistry.addName(Items.pickaxeStoneBedrock, "Bedrock Pickaxe");
        LanguageRegistry.addName(Items.swordBedrock, "Bedrock Sword");
        LanguageRegistry.addName(Items.swordStoneBedrock, "Bedrock Sword");
        LanguageRegistry.addName(Items.ingotTfarcenim, "Tfarcenim Ingot");
        LanguageRegistry.addName(Items.stickIron, "Iron Stick");
        LanguageRegistry.addName(Items.stickGold, "Gold Stick");
        LanguageRegistry.addName(Items.stickDiamond, "Diamond Stick");
        LanguageRegistry.addName(Items.stickBedrock, "Bedrock Stick");
        LanguageRegistry.addName(Items.pickaxeIronBedrock, "Bedrock Pickaxe");
        LanguageRegistry.addName(Items.pickaxeGoldBedrock, "Bedrock Pickaxe");
        LanguageRegistry.addName(Items.pickaxeDiamondBedrock, "Bedrock Pickaxe");
        LanguageRegistry.addName(Items.pickaxeBedrockBedrock, "Bedrock Pickaxe");
        LanguageRegistry.addName(Items.helmetBedrock, "Bedrock Helmet");
        LanguageRegistry.addName(Items.plateBedrock, "Bedrock Chestplate");
        LanguageRegistry.addName(Items.legsBedrock, "Bedrock Leggings");
        LanguageRegistry.addName(Items.bootsBedrock, "Bedrock Boots");
        LanguageRegistry.addName(Items.swordIronBedrock, "Bedrock Sword");
        LanguageRegistry.addName(Items.swordGoldBedrock, "Bedrock Sword");
        LanguageRegistry.addName(Items.swordDiamondBedrock, "Bedrock Sword");
        LanguageRegistry.addName(Items.swordBedrockBedrock, "Bedrock Sword");
        LanguageRegistry.addName(Items.spadeBedrock, "Bedrock Shovel");
        LanguageRegistry.addName(Items.spadeStoneBedrock, "Bedrock Shovel");
        LanguageRegistry.addName(Items.spadeIronBedrock, "Bedrock Shovel");
        LanguageRegistry.addName(Items.spadeGoldBedrock, "Bedrock Shovel");
        LanguageRegistry.addName(Items.spadeDiamondBedrock, "Bedrock Shovel");
        LanguageRegistry.addName(Items.spadeBedrockBedrock, "Bedrock Shovel");
        LanguageRegistry.addName(Items.hoeBedrock, "Bedrock Hoe");
        LanguageRegistry.addName(Items.hoeStoneBedrock, "Bedrock Hoe");
        LanguageRegistry.addName(Items.hoeIronBedrock, "Bedrock Hoe");
        LanguageRegistry.addName(Items.hoeGoldBedrock, "Bedrock Hoe");
        LanguageRegistry.addName(Items.hoeDiamondBedrock, "Bedrock Hoe");
        LanguageRegistry.addName(Items.hoeBedrockBedrock, "Bedrock Hoe");
        LanguageRegistry.addName(Items.axeBedrock, "Bedrock Axe");
        LanguageRegistry.addName(Items.axeStoneBedrock, "Bedrock Axe");
        LanguageRegistry.addName(Items.axeIronBedrock, "Bedrock Axe");
        LanguageRegistry.addName(Items.axeGoldBedrock, "Bedrock Axe");
        LanguageRegistry.addName(Items.axeDiamondBedrock, "Bedrock Axe");
        LanguageRegistry.addName(Items.axeBedrockBedrock, "Bedrock Axe");
        LanguageRegistry.addName(Items.pickaxeStoneDiamond, "Diamond Pickaxe");
        LanguageRegistry.addName(Items.pickaxeIronDiamond, "Diamond Pickaxe");
        LanguageRegistry.addName(Items.pickaxeGoldDiamond, "Diamond Pickaxe");
        LanguageRegistry.addName(Items.pickaxeDiamondDiamond, "Diamond Pickaxe");
        LanguageRegistry.addName(Items.pickaxeBedrockDiamond, "Diamond Pickaxe");
        LanguageRegistry.addName(Items.swordStoneDiamond, "Diamond Sword");
        LanguageRegistry.addName(Items.swordIronDiamond, "Diamond Sword");
        LanguageRegistry.addName(Items.swordGoldDiamond, "Diamond Sword");
        LanguageRegistry.addName(Items.swordDiamondDiamond, "Diamond Sword");
        LanguageRegistry.addName(Items.swordBedrockDiamond, "Diamond Sword");
        LanguageRegistry.addName(Items.axeStoneDiamond, "Diamond Axe");
        LanguageRegistry.addName(Items.axeIronDiamond, "Diamond Axe");
        LanguageRegistry.addName(Items.axeGoldDiamond, "Diamond Axe");
        LanguageRegistry.addName(Items.axeDiamondDiamond, "Diamond Axe");
        LanguageRegistry.addName(Items.axeBedrockDiamond, "Diamond Axe");
        LanguageRegistry.addName(Items.spadeStoneDiamond, "Diamond Shovel");
        LanguageRegistry.addName(Items.spadeIronDiamond, "Diamond Shovel");
        LanguageRegistry.addName(Items.spadeGoldDiamond, "Diamond Shovel");
        LanguageRegistry.addName(Items.spadeDiamondDiamond, "Diamond Shovel");
        LanguageRegistry.addName(Items.spadeBedrockDiamond, "Diamond Shovel");
        LanguageRegistry.addName(Items.hoeStoneDiamond, "Diamond Hoe");
        LanguageRegistry.addName(Items.hoeIronDiamond, "Diamond Hoe");
        LanguageRegistry.addName(Items.hoeGoldDiamond, "Diamond Hoe");
        LanguageRegistry.addName(Items.hoeDiamondDiamond, "Diamond Hoe");
        LanguageRegistry.addName(Items.hoeBedrockDiamond, "Diamond Hoe");
        LanguageRegistry.addName(Items.pickaxeStoneGold, "Gold Pickaxe");
        LanguageRegistry.addName(Items.pickaxeIronGold, "Gold Pickaxe");
        LanguageRegistry.addName(Items.pickaxeGoldGold, "Gold Pickaxe");
        LanguageRegistry.addName(Items.pickaxeDiamondGold, "Gold Pickaxe");
        LanguageRegistry.addName(Items.pickaxeBedrockGold, "Gold Pickaxe");
        LanguageRegistry.addName(Items.swordStoneGold, "Gold Sword");
        LanguageRegistry.addName(Items.swordIronGold, "Gold Sword");
        LanguageRegistry.addName(Items.swordGoldGold, "Gold Sword");
        LanguageRegistry.addName(Items.swordDiamondGold, "Gold Sword");
        LanguageRegistry.addName(Items.swordBedrockGold, "Gold Sword");
        LanguageRegistry.addName(Items.axeStoneGold, "Gold Axe");
        LanguageRegistry.addName(Items.axeIronGold, "Gold Axe");
        LanguageRegistry.addName(Items.axeGoldGold, "Gold Axe");
        LanguageRegistry.addName(Items.axeDiamondGold, "Gold Axe");
        LanguageRegistry.addName(Items.axeBedrockGold, "Gold Axe");
        LanguageRegistry.addName(Items.spadeStoneGold, "Gold Shovel");
        LanguageRegistry.addName(Items.spadeIronGold, "Gold Shovel");
        LanguageRegistry.addName(Items.spadeGoldGold, "Gold Shovel");
        LanguageRegistry.addName(Items.spadeDiamondGold, "Gold Shovel");
        LanguageRegistry.addName(Items.spadeBedrockGold, "Gold Shovel");
        LanguageRegistry.addName(Items.hoeStoneGold, "Gold Hoe");
        LanguageRegistry.addName(Items.hoeIronGold, "Gold Hoe");
        LanguageRegistry.addName(Items.hoeGoldGold, "Gold Hoe");
        LanguageRegistry.addName(Items.hoeDiamondGold, "Gold Hoe");
        LanguageRegistry.addName(Items.hoeBedrockGold, "Gold Hoe");
        LanguageRegistry.addName(Items.pickaxeStoneIron, "Iron Pickaxe");
        LanguageRegistry.addName(Items.pickaxeIronIron, "Iron Pickaxe");
        LanguageRegistry.addName(Items.pickaxeGoldIron, "Iron Pickaxe");
        LanguageRegistry.addName(Items.pickaxeDiamondIron, "Iron Pickaxe");
        LanguageRegistry.addName(Items.pickaxeBedrockIron, "Iron Pickaxe");
        LanguageRegistry.addName(Items.swordStoneIron, "Iron Sword");
        LanguageRegistry.addName(Items.swordIronIron, "Iron Sword");
        LanguageRegistry.addName(Items.swordGoldIron, "Iron Sword");
        LanguageRegistry.addName(Items.swordDiamondIron, "Iron Sword");
        LanguageRegistry.addName(Items.swordBedrockIron, "Iron Sword");
        LanguageRegistry.addName(Items.axeStoneIron, "Iron Axe");
        LanguageRegistry.addName(Items.axeIronIron, "Iron Axe");
        LanguageRegistry.addName(Items.axeGoldIron, "Iron Axe");
        LanguageRegistry.addName(Items.axeDiamondIron, "Iron Axe");
        LanguageRegistry.addName(Items.axeBedrockIron, "Iron Axe");
        LanguageRegistry.addName(Items.spadeStoneIron, "Iron Shovel");
        LanguageRegistry.addName(Items.spadeIronIron, "Iron Shovel");
        LanguageRegistry.addName(Items.spadeGoldIron, "Iron Shovel");
        LanguageRegistry.addName(Items.spadeDiamondIron, "Iron Shovel");
        LanguageRegistry.addName(Items.spadeBedrockIron, "Iron Shovel");
        LanguageRegistry.addName(Items.hoeStoneIron, "Iron Hoe");
        LanguageRegistry.addName(Items.hoeIronIron, "Iron Hoe");
        LanguageRegistry.addName(Items.hoeGoldIron, "Iron Hoe");
        LanguageRegistry.addName(Items.hoeDiamondIron, "Iron Hoe");
        LanguageRegistry.addName(Items.hoeBedrockIron, "Iron Hoe");
        LanguageRegistry.addName(Items.pickaxeStoneStone, "Stone Pickaxe");
        LanguageRegistry.addName(Items.pickaxeIronStone, "Stone Pickaxe");
        LanguageRegistry.addName(Items.pickaxeGoldStone, "Stone Pickaxe");
        LanguageRegistry.addName(Items.pickaxeDiamondStone, "Stone Pickaxe");
        LanguageRegistry.addName(Items.pickaxeBedrockStone, "Stone Pickaxe");
        LanguageRegistry.addName(Items.swordStoneStone, "Stone Sword");
        LanguageRegistry.addName(Items.swordIronStone, "Stone Sword");
        LanguageRegistry.addName(Items.swordGoldStone, "Stone Sword");
        LanguageRegistry.addName(Items.swordDiamondStone, "Stone Sword");
        LanguageRegistry.addName(Items.swordBedrockStone, "Stone Sword");
        LanguageRegistry.addName(Items.axeStoneStone, "Stone Axe");
        LanguageRegistry.addName(Items.axeIronStone, "Stone Axe");
        LanguageRegistry.addName(Items.axeGoldStone, "Stone Axe");
        LanguageRegistry.addName(Items.axeDiamondStone, "Stone Axe");
        LanguageRegistry.addName(Items.axeBedrockStone, "Stone Axe");
        LanguageRegistry.addName(Items.spadeStoneStone, "Stone Shovel");
        LanguageRegistry.addName(Items.spadeIronStone, "Stone Shovel");
        LanguageRegistry.addName(Items.spadeGoldStone, "Stone Shovel");
        LanguageRegistry.addName(Items.spadeDiamondStone, "Stone Shovel");
        LanguageRegistry.addName(Items.spadeBedrockStone, "Stone Shovel");
        LanguageRegistry.addName(Items.hoeStoneStone, "Stone Hoe");
        LanguageRegistry.addName(Items.hoeIronStone, "Stone Hoe");
        LanguageRegistry.addName(Items.hoeGoldStone, "Stone Hoe");
        LanguageRegistry.addName(Items.hoeDiamondStone, "Stone Hoe");
        LanguageRegistry.addName(Items.hoeBedrockStone, "Stone Hoe");
        LanguageRegistry.addName(Items.pickaxeStoneWood, "Wooden Pickaxe");
        LanguageRegistry.addName(Items.pickaxeIronWood, "Wooden Pickaxe");
        LanguageRegistry.addName(Items.pickaxeGoldWood, "Wooden Pickaxe");
        LanguageRegistry.addName(Items.pickaxeDiamondWood, "Wooden Pickaxe");
        LanguageRegistry.addName(Items.pickaxeBedrockWood, "Wooden Pickaxe");
        LanguageRegistry.addName(Items.swordStoneWood, "Wooden Sword");
        LanguageRegistry.addName(Items.swordIronWood, "Wooden Sword");
        LanguageRegistry.addName(Items.swordGoldWood, "Wooden Sword");
        LanguageRegistry.addName(Items.swordDiamondWood, "Wooden Sword");
        LanguageRegistry.addName(Items.swordBedrockWood, "Wooden Sword");
        LanguageRegistry.addName(Items.axeStoneWood, "Wooden Axe");
        LanguageRegistry.addName(Items.axeIronWood, "Wooden Axe");
        LanguageRegistry.addName(Items.axeGoldWood, "Wooden Axe");
        LanguageRegistry.addName(Items.axeDiamondWood, "Wooden Axe");
        LanguageRegistry.addName(Items.axeBedrockWood, "Wooden Axe");
        LanguageRegistry.addName(Items.spadeStoneWood, "Wooden Shovel");
        LanguageRegistry.addName(Items.spadeIronWood, "Wooden Shovel");
        LanguageRegistry.addName(Items.spadeGoldWood, "Wooden Shovel");
        LanguageRegistry.addName(Items.spadeDiamondWood, "Wooden Shovel");
        LanguageRegistry.addName(Items.spadeBedrockWood, "Wooden Shovel");
        LanguageRegistry.addName(Items.hoeStoneWood, "Wooden Hoe");
        LanguageRegistry.addName(Items.hoeIronWood, "Wooden Hoe");
        LanguageRegistry.addName(Items.hoeGoldWood, "Wooden Hoe");
        LanguageRegistry.addName(Items.hoeDiamondWood, "Wooden Hoe");
        LanguageRegistry.addName(Items.hoeBedrockWood, "Wooden Hoe");
        LanguageRegistry.addName(Items.swordInstaKill, "Insta-Kill Sword");
        LanguageRegistry.addName(Items.lambRaw, "Raw Lamb Chops");
        LanguageRegistry.addName(Items.lambCooked, "Cooked Mutton");
        LanguageRegistry.addName(Items.swordInfinity, "Infinity Sword");
        LanguageRegistry.addName(Items.pickaxeInfinity, "Infinity Pickaxe");
        LanguageRegistry.addName(Items.axeInfinity, "Infinity Axe");
        LanguageRegistry.addName(Items.spadeInfinity, "Infinity Shovel");
        LanguageRegistry.addName(Items.hoeInfinity, "Infinity Hoe");
        LanguageRegistry.addName(Items.crystalNormal, "Unfused Crystal");
        LanguageRegistry.addName(Items.crystalSuper, "Unfused Super Crystal");
        LanguageRegistry.addName(Items.crystalUltra, "Unfused Ultra Crystal");
        LanguageRegistry.addName(Items.crystalInfinity, "Unfused Infinity Crystal");
        LanguageRegistry.addName(Items.crystalNormalFused, "Fused Crystal");
        LanguageRegistry.addName(Items.crystalSuperFused, "Fused Super Crystal");
        LanguageRegistry.addName(Items.crystalUltraFused, "Fused Ultra Crystal");
        LanguageRegistry.addName(Items.crystalInfinityFused, "Fused Infinity Crystal");
        LanguageRegistry.addName(Items.bowInsta, "Insta Bow");
        LanguageRegistry.addName(Items.stringDiamond, "Diamond String");
        LanguageRegistry.addName(Blocks.leaves, "Apple Leaves");
        LanguageRegistry.addName(Blocks.sapling, "Apple Sapling");
        LanguageRegistry.addName(Items.appleSeeds, "Apple Seeds");
        LanguageRegistry.addName(Blocks.appleCrop, "Apple Crops");
        LanguageRegistry.addName(Blocks.stoneNoHit, "Intangible Stone");
        LanguageRegistry.addName(Blocks.cobblestoneNoHit, "Intangible Cobblestone");
        LanguageRegistry.addName(Blocks.cutter, "Cutter");
        LanguageRegistry.addName(Items.piecesGold, "Gold Pieces");
        LanguageRegistry.addName(Items.piecesIron, "Iron Pieces");
        LanguageRegistry.addName(Items.dyeRainbow, "Rainbow Dye");
        LanguageRegistry.addName(Blocks.woolRainbow, "Rainbow Wool");
        LanguageRegistry.addName(Items.piecesTfarcenim, "Tfarcenim Pieces");
        LanguageRegistry.addName(Items.dustDiamond, "Diamond Dust");
        LanguageRegistry.addName(Blocks.oreIntangible, "Intangible Ore");
        LanguageRegistry.addName(Items.essenceIntangible, "Intangible Essence");
        LanguageRegistry.addName(Blocks.flowerRainbow, "Rainbow Flower");
        LanguageRegistry.addName(Items.itemFlowerRainbow, "Rainbow Flower");
        LanguageRegistry.addName(Blocks.woolRainbowNoHit, "Intangible Rainbow Wool");
        LanguageRegistry.addName(Blocks.glassNoHit, "Intangible Glass");
        LanguageRegistry.addName(Blocks.chestNether, "Nether Chest");
        LanguageRegistry.addName(Blocks.fuser, "Fuser");
        LanguageRegistry.addName(new ItemStack(Blocks.planksNoHit, 1, 0), "Intangible Oak Planks");
        LanguageRegistry.addName(new ItemStack(Blocks.planksNoHit, 1, 1), "Intangible Spruce Planks");
        LanguageRegistry.addName(new ItemStack(Blocks.planksNoHit, 1, 2), "Intangible Birch Planks");
        LanguageRegistry.addName(new ItemStack(Blocks.planksNoHit, 1, 3), "Intangible Jungle Planks");
        LanguageRegistry.addName(Items.recordSideburns, "Music Disc");
        LanguageRegistry.addName(Items.hammer, "Hammer");
        LanguageRegistry.addName(Items.crystalNormalFused, "Fused Normal Crystal");
        LanguageRegistry.addName(Items.recordDramatic, "Music Disc");
        MinecraftForge.setBlockHarvestLevel(Blocks.oreBedrock, "pickaxe", 3);
        MinecraftForge.setBlockHarvestLevel(Blocks.oreTfarcenim, "pickaxe", 2);
        MinecraftForge.setBlockHarvestLevel(Blocks.blockBedrock, "pickaxe", 4);
        MinecraftForge.setBlockHarvestLevel(Blocks.blockTfarcenim, "pickaxe", 2);
        MinecraftForge.setBlockHarvestLevel(Blocks.oreIntangible, "pickaxe", 3);
        GameRegistry.addSmelting(Blocks.oreTfarcenim.blockID, new ItemStack(Items.ingotTfarcenim), 0.8F);
        GameRegistry.addSmelting(Items.lambRaw.itemID, new ItemStack(Items.lambCooked), 0.35F);
        GameRegistry.addSmelting(Items.piecesIron.itemID, new ItemStack(Item.ingotIron), 0.7F);
        GameRegistry.addSmelting(Items.piecesGold.itemID, new ItemStack(Item.ingotGold), 1.0F);
        GameRegistry.addSmelting(Items.piecesTfarcenim.itemID, new ItemStack(Items.ingotTfarcenim), 0.8F);
        GameRegistry.addSmelting(Blocks.cobblestoneNoHit.blockID, new ItemStack(Blocks.stoneNoHit), 0.1F);
        GameRegistry.addSmelting(Items.dustDiamond.itemID, new ItemStack(Item.diamond), 0.1F);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeBedrock), "xxx", " y ", " y ", 'x', Items.piecesBedrock, 'y', Item.stick);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeStoneBedrock), "xxx", " y ", " y ", 'x', Items.piecesBedrock, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.stickStone, 2), "x", "x", 'x', Block.stone);
        GameRegistry.addRecipe(new ItemStack(Items.swordBedrock), "x", "x", "y", 'x', Items.piecesBedrock, 'y', Item.stick);
        GameRegistry.addRecipe(new ItemStack(Items.swordStoneBedrock), "x", "x", "y", 'x', Items.piecesBedrock, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.swordIronBedrock), "x", "x", "y", 'x', Items.piecesBedrock, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.swordGoldBedrock), "x", "x", "y", 'x', Items.piecesBedrock, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.swordDiamondBedrock), "x", "x", "y", 'x', Items.piecesBedrock, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.swordBedrockBedrock), "x", "x", "y", 'x', Items.piecesBedrock, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeIronBedrock), "xxx", " y ", " y ", 'x', Items.piecesBedrock, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeGoldBedrock), "xxx", " y ", " y ", 'x', Items.piecesBedrock, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeDiamondBedrock), "xxx", " y ", " y ", 'x', Items.piecesBedrock, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeBedrockBedrock), "xxx", " y ", " y ", 'x', Items.piecesBedrock, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.stickIron, 2), "x", "x", 'x', Item.ingotIron);
        GameRegistry.addRecipe(new ItemStack(Items.stickGold, 2), "x", "x", 'x', Item.ingotGold);
        GameRegistry.addRecipe(new ItemStack(Items.stickDiamond, 2), "x", "x", 'x', Item.diamond);
        GameRegistry.addRecipe(new ItemStack(Items.stickBedrock, 2), "x", "x", 'x', Items.piecesBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.helmetBedrock), "xxx", "x x", 'x', Items.piecesBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.plateBedrock), "x x", "xxx", "xxx", 'x', Items.piecesBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.legsBedrock), "xxx", "x x", "x x", 'x', Items.piecesBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.bootsBedrock), "x x", "x x", 'x', Items.piecesBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrock), "xx", "xy", " y", 'x', Items.piecesBedrock, 'y', Item.stick);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneBedrock), "xx", "xy", " y", 'x', Items.piecesBedrock, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronBedrock), "xx", "xy", " y", 'x', Items.piecesBedrock, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldBedrock), "xx", "xy", " y", 'x', Items.piecesBedrock, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondBedrock), "xx", "xy", " y", 'x', Items.piecesBedrock, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockBedrock), "xx", "xy", " y", 'x', Items.piecesBedrock, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrock), " xx", "yx", "y ", 'x', Items.piecesBedrock, 'y', Item.stick);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneBedrock), "xx", "yx", "y ", 'x', Items.piecesBedrock, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronBedrock), "xx", "yx", "y ", 'x', Items.piecesBedrock, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldBedrock), "xx", "yx", "y ", 'x', Items.piecesBedrock, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondBedrock), "xx", "yx", "y ", 'x', Items.piecesBedrock, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockBedrock), "xx", "yx", "y ", 'x', Items.piecesBedrock, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.spadeBedrock), "x", "y", "y", 'x', Items.piecesBedrock, 'y', Item.stick);
        GameRegistry.addRecipe(new ItemStack(Items.spadeStoneBedrock), "x", "y", "y", 'x', Items.piecesBedrock, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.spadeIronBedrock), "x", "y", "y", 'x', Items.piecesBedrock, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.spadeGoldBedrock), "x", "y", "y", 'x', Items.piecesBedrock, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.spadeDiamondBedrock), "x", "y", "y", 'x', Items.piecesBedrock, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.spadeBedrockBedrock), "x", "y", "y", 'x', Items.piecesBedrock, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.hoeBedrock), "xx", "y ", "y ", 'x', Items.piecesBedrock, 'y', Item.stick);
        GameRegistry.addRecipe(new ItemStack(Items.hoeStoneBedrock), "xx", "y ", "y ", 'x', Items.piecesBedrock, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.hoeIronBedrock), "xx", "y ", "y ", 'x', Items.piecesBedrock, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.hoeGoldBedrock), "xx", "y ", "y ", 'x', Items.piecesBedrock, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.hoeDiamondBedrock), "xx", "y ", "y ", 'x', Items.piecesBedrock, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.hoeBedrockBedrock), "xx", "y ", "y ", 'x', Items.piecesBedrock, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Blocks.blockBedrock), "xxx", "xxx", "xxx", 'x', Items.piecesBedrock);
        GameRegistry.addRecipe(new ItemStack(Blocks.blockTfarcenim), "xxx", "xxx", "xxx", 'x', Items.ingotTfarcenim);
        GameRegistry.addShapelessRecipe(new ItemStack(Items.piecesBedrock, 9), new ItemStack(Blocks.blockBedrock));
        GameRegistry.addShapelessRecipe(new ItemStack(Items.ingotTfarcenim, 9), new ItemStack(Blocks.blockTfarcenim));
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeStoneDiamond), "xxx", " y ", " y ", 'x', Item.diamond, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeIronDiamond), "xxx", " y ", " y ", 'x', Item.diamond, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeGoldDiamond), "xxx", " y ", " y ", 'x', Item.diamond, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeDiamondDiamond), "xxx", " y ", " y ", 'x', Item.diamond, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeBedrockDiamond), "xxx", " y ", " y ", 'x', Item.diamond, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeStoneGold), "xxx", " y ", " y ", 'x', Item.ingotGold, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeIronGold), "xxx", " y ", " y ", 'x', Item.ingotGold, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeGoldGold), "xxx", " y ", " y ", 'x', Item.ingotGold, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeDiamondGold), "xxx", " y ", " y ", 'x', Item.ingotGold, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeBedrockGold), "xxx", " y ", " y ", 'x', Item.ingotGold, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeStoneIron), "xxx", " y ", " y ", 'x', Item.ingotIron, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeIronIron), "xxx", " y ", " y ", 'x', Item.ingotIron, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeGoldIron), "xxx", " y ", " y ", 'x', Item.ingotIron, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeDiamondIron), "xxx", " y ", " y ", 'x', Item.ingotIron, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeBedrockIron), "xxx", " y ", " y ", 'x', Item.ingotIron, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeStoneStone), "xxx", " y ", " y ", 'x', Block.cobblestone, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeIronStone), "xxx", " y ", " y ", 'x', Block.cobblestone, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeGoldStone), "xxx", " y ", " y ", 'x', Block.cobblestone, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeDiamondStone), "xxx", " y ", " y ", 'x', Block.cobblestone, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeBedrockStone), "xxx", " y ", " y ", 'x', Block.cobblestone, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeStoneWood), "xxx", " y ", " y ", 'x', Block.planks, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeIronWood), "xxx", " y ", " y ", 'x', Block.planks, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeGoldWood), "xxx", " y ", " y ", 'x', Block.planks, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeDiamondWood), "xxx", " y ", " y ", 'x', Block.planks, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeBedrockWood), "xxx", " y ", " y ", 'x', Block.planks, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.swordStoneDiamond), "x", "x", "y", 'x', Item.diamond, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.swordIronDiamond), "x", "x", "y", 'x', Item.diamond, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.swordGoldDiamond), "x", "x", "y", 'x', Item.diamond, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.swordDiamondDiamond), "x", "x", "y", 'x', Item.diamond, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.swordBedrockDiamond), "x", "x", "y", 'x', Item.diamond, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.swordStoneGold), "x", "x", "y", 'x', Item.ingotGold, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.swordIronGold), "x", "x", "y", 'x', Item.ingotGold, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.swordGoldGold), "x", "x", "y", 'x', Item.ingotGold, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.swordDiamondGold), "x", "x", "y", 'x', Item.ingotGold, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.swordBedrockGold), "x", "x", "y", 'x', Item.ingotGold, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.swordStoneIron), "x", "x", "y", 'x', Item.ingotIron, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.swordIronIron), "x", "x", "y", 'x', Item.ingotIron, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.swordGoldIron), "x", "x", "y", 'x', Item.ingotIron, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.swordDiamondIron), "x", "x", "y", 'x', Item.ingotIron, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.swordBedrockIron), "x", "x", "y", 'x', Item.ingotIron, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.swordStoneStone), "x", "x", "y", 'x', Block.cobblestone, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.swordIronStone), "x", "x", "y", 'x', Block.cobblestone, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.swordGoldStone), "x", "x", "y", 'x', Block.cobblestone, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.swordDiamondStone), "x", "x", "y", 'x', Block.cobblestone, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.swordBedrockStone), "x", "x", "y", 'x', Block.cobblestone, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.swordStoneWood), "x", "x", "y", 'x', Block.planks, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.swordIronWood), "x", "x", "y", 'x', Block.planks, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.swordGoldWood), "x", "x", "y", 'x', Block.planks, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.swordDiamondWood), "x", "x", "y", 'x', Block.planks, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.swordBedrockWood), "x", "x", "y", 'x', Block.planks, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneDiamond), "xx", "xy", " y", 'x', Item.diamond, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronDiamond), "xx", "xy", " y", 'x', Item.diamond, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldDiamond), "xx", "xy", " y", 'x', Item.diamond, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondDiamond), "xx", "xy", " y", 'x', Item.diamond, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockDiamond), "xx", "xy", " y", 'x', Item.diamond, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneGold), "xx", "xy", " y", 'x', Item.ingotGold, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronGold), "xx", "xy", " y", 'x', Item.ingotGold, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldGold), "xx", "xy", " y", 'x', Item.ingotGold, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondGold), "xx", "xy", " y", 'x', Item.ingotGold, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockGold), "xx", "xy", " y", 'x', Item.ingotGold, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneIron), "xx", "xy", " y", 'x', Item.ingotIron, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronIron), "xx", "xy", " y", 'x', Item.ingotIron, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldIron), "xx", "xy", " y", 'x', Item.ingotIron, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondIron), "xx", "xy", " y", 'x', Item.ingotIron, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockIron), "xx", "xy", " y", 'x', Item.ingotIron, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneStone), "xx", "xy", " y", 'x', Block.cobblestone, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronStone), "xx", "xy", " y", 'x', Block.cobblestone, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldStone), "xx", "xy", " y", 'x', Block.cobblestone, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondStone), "xx", "xy", " y", 'x', Block.cobblestone, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockStone), "xx", "xy", " y", 'x', Block.cobblestone, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneWood), "xx", "xy", " y", 'x', Block.planks, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronWood), "xx", "xy", " y", 'x', Block.planks, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldWood), "xx", "xy", " y", 'x', Block.planks, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondWood), "xx", "xy", " y", 'x', Block.planks, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockWood), "xx", "xy", " y", 'x', Block.planks, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneDiamond), "xx", "yx", "y ", 'x', Item.diamond, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronDiamond), "xx", "yx", "y ", 'x', Item.diamond, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldDiamond), "xx", "yx", "y ", 'x', Item.diamond, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondDiamond), "xx", "yx", "y ", 'x', Item.diamond, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockDiamond), "xx", "yx", "y ", 'x', Item.diamond, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneGold), "xx", "yx", "y ", 'x', Item.ingotGold, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronGold), "xx", "yx", "y ", 'x', Item.ingotGold, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldGold), "xx", "yx", "y ", 'x', Item.ingotGold, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondGold), "xx", "yx", "y ", 'x', Item.ingotGold, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockGold), "xx", "yx", "y ", 'x', Item.ingotGold, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneIron), "xx", "yx", "y ", 'x', Item.ingotIron, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronIron), "xx", "yx", "y ", 'x', Item.ingotIron, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldIron), "xx", "yx", "y ", 'x', Item.ingotIron, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondIron), "xx", "yx", "y ", 'x', Item.ingotIron, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockIron), "xx", "yx", "y ", 'x', Item.ingotIron, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneStone), "xx", "yx", "y ", 'x', Block.cobblestone, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronStone), "xx", "yx", "y ", 'x', Block.cobblestone, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldStone), "xx", "yx", "y ", 'x', Block.cobblestone, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondStone), "xx", "yx", "y ", 'x', Block.cobblestone, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockStone), "xx", "yx", "y ", 'x', Block.cobblestone, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeStoneWood), "xx", "yx", "y ", 'x', Block.planks, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.axeIronWood), "xx", "yx", "y ", 'x', Block.planks, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.axeGoldWood), "xx", "yx", "y ", 'x', Block.planks, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.axeDiamondWood), "xx", "yx", "y ", 'x', Block.planks, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.axeBedrockWood), "xx", "yx", "y ", 'x', Block.planks, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.spadeStoneDiamond), "x", "y", "y", 'x', Item.diamond, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.spadeIronDiamond), "x", "y", "y", 'x', Item.diamond, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.spadeGoldDiamond), "x", "y", "y", 'x', Item.diamond, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.spadeDiamondDiamond), "x", "y", "y", 'x', Item.diamond, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.spadeBedrockDiamond), "x", "y", "y", 'x', Item.diamond, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.spadeStoneGold), "x", "y", "y", 'x', Item.ingotGold, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.spadeIronGold), "x", "y", "y", 'x', Item.ingotGold, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.spadeGoldGold), "x", "y", "y", 'x', Item.ingotGold, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.spadeDiamondGold), "x", "y", "y", 'x', Item.ingotGold, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.spadeBedrockGold), "x", "y", "y", 'x', Item.ingotGold, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.spadeStoneIron), "x", "y", "y", 'x', Item.ingotIron, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.spadeIronIron), "x", "y", "y", 'x', Item.ingotIron, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.spadeGoldIron), "x", "y", "y", 'x', Item.ingotIron, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.spadeDiamondIron), "x", "y", "y", 'x', Item.ingotIron, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.spadeBedrockIron), "x", "y", "y", 'x', Item.ingotIron, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.spadeStoneStone), "x", "y", "y", 'x', Block.cobblestone, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.spadeIronStone), "x", "y", "y", 'x', Block.cobblestone, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.spadeGoldStone), "x", "y", "y", 'x', Block.cobblestone, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.spadeDiamondStone), "x", "y", "y", 'x', Block.cobblestone, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.spadeBedrockStone), "x", "y", "y", 'x', Block.cobblestone, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.spadeStoneWood), "x", "y", "y", 'x', Block.planks, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.spadeIronWood), "x", "y", "y", 'x', Block.planks, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.spadeGoldWood), "x", "y", "y", 'x', Block.planks, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.spadeDiamondWood), "x", "y", "y", 'x', Block.planks, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.spadeBedrockWood), "x", "y", "y", 'x', Block.planks, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.hoeStoneDiamond), "xx", "y ", "y ", 'x', Item.diamond, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.hoeIronDiamond), "xx", "y ", "y ", 'x', Item.diamond, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.hoeGoldDiamond), "xx", "y ", "y ", 'x', Item.diamond, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.hoeDiamondDiamond), "xx", "y ", "y ", 'x', Item.diamond, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.hoeBedrockDiamond), "xx", "y ", "y ", 'x', Item.diamond, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.hoeStoneGold), "xx", "y ", "y ", 'x', Item.ingotGold, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.hoeIronGold), "xx", "y ", "y ", 'x', Item.ingotGold, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.hoeGoldGold), "xx", "y ", "y ", 'x', Item.ingotGold, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.hoeDiamondGold), "xx", "y ", "y ", 'x', Item.ingotGold, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.hoeBedrockGold), "xx", "y ", "y ", 'x', Item.ingotGold, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.hoeStoneIron), "xx", "y ", "y ", 'x', Item.ingotIron, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.hoeIronIron), "xx", "y ", "y ", 'x', Item.ingotIron, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.hoeGoldIron), "xx", "y ", "y ", 'x', Item.ingotIron, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.hoeDiamondIron), "xx", "y ", "y ", 'x', Item.ingotIron, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.hoeBedrockIron), "xx", "y ", "y ", 'x', Item.ingotIron, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.hoeStoneStone), "xx", "y ", "y ", 'x', Block.cobblestone, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.hoeIronStone), "xx", "y ", "y ", 'x', Block.cobblestone, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.hoeGoldStone), "xx", "y ", "y ", 'x', Block.cobblestone, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.hoeDiamondStone), "xx", "y ", "y ", 'x', Block.cobblestone, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.hoeBedrockStone), "xx", "y ", "y ", 'x', Block.cobblestone, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.hoeStoneWood), "xx", "y ", "y ", 'x', Block.planks, 'y', Items.stickStone);
        GameRegistry.addRecipe(new ItemStack(Items.hoeIronWood), "xx", "y ", "y ", 'x', Block.planks, 'y', Items.stickIron);
        GameRegistry.addRecipe(new ItemStack(Items.hoeGoldWood), "xx", "y ", "y ", 'x', Block.planks, 'y', Items.stickGold);
        GameRegistry.addRecipe(new ItemStack(Items.hoeDiamondWood), "xx", "y ", "y ", 'x', Block.planks, 'y', Items.stickDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.hoeBedrockWood), "xx", "y ", "y ", 'x', Block.planks, 'y', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.swordInstaKill), "yxy", "xsx", "dgd", 'x', Item.ingotGold, 'y', Items.ingotTfarcenim, 's', Items.swordGoldGold, 'g', Items.stickGold, 'd', Item.diamond);
        GameRegistry.addRecipe(new ItemStack(Items.pickaxeInfinity), "ccc", "dbd", "dbd", 'c', Items.crystalInfinityFused, 'd', Item.diamond, 'b', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.swordInfinity), " c ", " c ", "dbd", 'c', Items.crystalInfinityFused, 'd', Item.diamond, 'b', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeInfinity), "cc ", "cbd", "dbd", 'c', Items.crystalInfinityFused, 'd', Item.diamond, 'b', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.axeInfinity), " cc", "dbc", "dbd", 'c', Items.crystalInfinityFused, 'd', Item.diamond, 'b', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.spadeInfinity), " c ", "dbd", "dbd", 'c', Items.crystalInfinityFused, 'd', Item.diamond, 'b', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.hoeInfinity), "cc ", "dbd", "dbd", 'c', Items.crystalInfinityFused, 'd', Item.diamond, 'b', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.hoeInfinity), " cc", "dbd", "dbd", 'c', Items.crystalInfinityFused, 'd', Item.diamond, 'b', Items.stickBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.bowInsta), " ds", "d s", " ds", 'd', Items.stickDiamond, 's', Items.stringDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.bowInsta), "sd ", "s d", "sd ", 'd', Items.stickDiamond, 's', Items.stringDiamond);
        GameRegistry.addRecipe(new ItemStack(Items.crystalNormal), " d ", "drd", " d ", 'd', Item.diamond, 'r', Item.redstone);
        GameRegistry.addRecipe(new ItemStack(Items.crystalSuper), "axa", "bcb", "axa", 'x', Items.crystalNormal, 'a', Item.diamond, 'b', Items.ingotTfarcenim, 'c', Item.ingotGold);
        GameRegistry.addRecipe(new ItemStack(Items.crystalUltra), "axa", "dbd", "axa", 'x', Items.crystalSuper, 'a', Items.crystalNormal, 'b', Items.piecesBedrock, 'd', Items.ingotTfarcenim);
        GameRegistry.addRecipe(new ItemStack(Items.crystalInfinity), "cxc", "aba", "cxc", 'x', Items.crystalUltra, 'a', Items.crystalSuper, 'b', Item.netherStar, 'c', Items.crystalNormal);
        GameRegistry.addRecipe(new ItemStack(Item.saddle), "lll", "ltl", "i i", 'l', Item.leather, 'i', Item.ingotIron, 't', Items.ingotTfarcenim);
        GameRegistry.addRecipe(new ItemStack(Item.nameTag), "itt", "tpp", "tpp", 'i', Item.ingotIron, 't', Items.ingotTfarcenim, 'p', Item.paper);
        GameRegistry.addRecipe(new ItemStack(Item.nameTag), "tti", "ppt", "ppt", 'i', Item.ingotIron, 't', Items.ingotTfarcenim, 'p', Item.paper);
        GameRegistry.addRecipe(new ItemStack(Blocks.cutter), "oxo", "xdx", "oxo", 'o', Block.obsidian, 'd', Item.diamond, 'x', Item.ingotIron);
        GameRegistry.addRecipe(new ItemStack(Blocks.stoneNoHit, 2), "xxx", "xyx", "xxx", 'x', Block.stone, 'y', Items.essenceIntangible);
        GameRegistry.addRecipe(new ItemStack(Blocks.cobblestoneNoHit, 2), "xxx", "xyx", "xxx", 'x', Block.cobblestone, 'y', Items.essenceIntangible);
        GameRegistry.addRecipe(new ItemStack(Blocks.woolRainbowNoHit, 2), "xxx", "xyx", "xxx", 'x', Blocks.woolRainbow, 'y', Items.essenceIntangible);
        GameRegistry.addRecipe(new ItemStack(Blocks.glassNoHit, 2), "xxx", "xyx", "xxx", 'x', Block.glass, 'y', Items.essenceIntangible);
        GameRegistry.addRecipe(new ItemStack(Blocks.chestNether), "nbn", "qcq", "nbn", 'n', Block.netherBrick, 'b', Item.blazeRod, 'q', Item.netherQuartz, 'c', Block.chest);
        GameRegistry.addRecipe(new ItemStack(Blocks.planksNoHit, 2, 0), "xxx", "xyx", "xxx", 'x', new ItemStack(Block.planks, 1, 0), 'y', Items.essenceIntangible);
        GameRegistry.addRecipe(new ItemStack(Blocks.planksNoHit, 2, 1), "xxx", "xyx", "xxx", 'x', new ItemStack(Block.planks, 1, 1), 'y', Items.essenceIntangible);
        GameRegistry.addRecipe(new ItemStack(Blocks.planksNoHit, 2, 2), "xxx", "xyx", "xxx", 'x', new ItemStack(Block.planks, 1, 2), 'y', Items.essenceIntangible);
        GameRegistry.addRecipe(new ItemStack(Blocks.planksNoHit, 2, 3), "xxx", "xyx", "xxx", 'x', new ItemStack(Block.planks, 1, 3), 'y', Items.essenceIntangible);
        GameRegistry.addRecipe(new ItemStack(Items.hammer), "ttt", "tyt", " y ", 'y', Item.stick, 't', Items.ingotTfarcenim);
        GameRegistry.addRecipe(new ItemStack(Items.crystalSuper), " x ", "bcb",  " x ", 'x', Items.crystalNormalFused, 'b', Items.ingotTfarcenim, 'c', Item.ingotGold);
        GameRegistry.addRecipe(new ItemStack(Items.crystalUltra), " x ", "aba", " x ", 'x', Items.crystalSuperFused, 'a', Items.crystalNormalFused, 'b', Items.piecesBedrock);
        GameRegistry.addRecipe(new ItemStack(Items.crystalInfinity), "dxd", "dbd", "dsd", 'x', Items.crystalUltraFused, 'b', Item.netherStar, 'd', Item.diamond, 's', Items.crystalSuperFused);
        GameRegistry.addRecipe(new ItemStack(Blocks.fuser), "xyx", "fcr", "xyx", 'f', Block.furnaceIdle, 'c', Blocks.cutter, 'r', Block.workbench, 'x', Blocks.blockTfarcenim, 'y', Items.piecesBedrock);
        GameRegistry.addShapelessRecipe(new ItemStack(Items.stringDiamond, 3), new ItemStack(Items.dustDiamond), new ItemStack(Item.silk), new ItemStack(Item.silk), new ItemStack(Item.silk));
        GameRegistry.addShapelessRecipe(new ItemStack(Items.appleSeeds), new ItemStack(Item.appleRed));
        GameRegistry.addShapelessRecipe(new ItemStack(Items.dyeRainbow, 2), new ItemStack(Blocks.flowerRainbow));
        GameRegistry.addShapelessRecipe(new ItemStack(Blocks.woolRainbow), new ItemStack(Block.cloth, 1, 0), new ItemStack(Items.dyeRainbow));
        GameRegistry.registerWorldGenerator(new WorldGenHandle());
        MinecraftForge.setToolClass(Items.pickaxeBedrock, "pickaxe", 4);
        MinecraftForge.setToolClass(Items.pickaxeStoneBedrock, "pickaxe", 4);
        MinecraftForge.setToolClass(Items.pickaxeIronBedrock, "pickaxe", 4);
        MinecraftForge.setToolClass(Items.pickaxeGoldBedrock, "pickaxe", 4);
        MinecraftForge.setToolClass(Items.pickaxeDiamondBedrock, "pickaxe", 4);
        MinecraftForge.setToolClass(Items.pickaxeBedrockBedrock, "pickaxe", 4);
        MinecraftForge.setToolClass(Items.pickaxeStoneDiamond, "pickaxe", 3);
        MinecraftForge.setToolClass(Items.pickaxeIronDiamond, "pickaxe", 3);
        MinecraftForge.setToolClass(Items.pickaxeGoldDiamond, "pickaxe", 3);
        MinecraftForge.setToolClass(Items.pickaxeDiamondDiamond, "pickaxe", 3);
        MinecraftForge.setToolClass(Items.pickaxeBedrockDiamond, "pickaxe", 3);
        MinecraftForge.setToolClass(Items.pickaxeStoneGold, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeIronGold, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeGoldGold, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeDiamondGold, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeBedrockGold, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeStoneIron, "pickaxe", 2);
        MinecraftForge.setToolClass(Items.pickaxeIronIron, "pickaxe", 2);
        MinecraftForge.setToolClass(Items.pickaxeGoldIron, "pickaxe", 2);
        MinecraftForge.setToolClass(Items.pickaxeDiamondIron, "pickaxe", 2);
        MinecraftForge.setToolClass(Items.pickaxeBedrockIron, "pickaxe", 2);
        MinecraftForge.setToolClass(Items.pickaxeStoneStone, "pickaxe", 1);
        MinecraftForge.setToolClass(Items.pickaxeIronStone, "pickaxe", 1);
        MinecraftForge.setToolClass(Items.pickaxeGoldStone, "pickaxe", 1);
        MinecraftForge.setToolClass(Items.pickaxeDiamondStone, "pickaxe", 1);
        MinecraftForge.setToolClass(Items.pickaxeBedrockStone, "pickaxe", 1);
        MinecraftForge.setToolClass(Items.pickaxeStoneWood, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeIronWood, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeGoldWood, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeDiamondWood, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeBedrockWood, "pickaxe", 0);
        MinecraftForge.setToolClass(Items.pickaxeInfinity, "pickaxe", 4);
        MinecraftForge.EVENT_BUS.register(new MobDrops());
        MinecraftForge.EVENT_BUS.register(new BonemealEvent());
        MinecraftForge.EVENT_BUS.register(new PlayerEvent());
        NetworkRegistry.instance().registerGuiHandler(this, new GuiHandler());
        GameRegistry.registerTileEntity(TileEntityCutter.class, "Cutter");
        GameRegistry.registerTileEntity(TileEntityNetherChest.class, "NetherChest");
        GameRegistry.registerTileEntity(TileEntityFuser.class, "Fuser");
        BlockFire.setBurnProperties(Blocks.leaves.blockID, 30, 60);
    }
    public static CreativeTabs tabInfinityBound = new CreativeTabs("tabInfinityBound")
    {
        public ItemStack getIconItemStack()
        {
            return new ItemStack(Items.crystalInfinityFused, 1, 0);
        }
    };
}